batch_size: 16
d_model: 128
decay_epochs: 18
dff: 512
dropout_rate: 0.1
final_lr: 0.0001
init_lr: 1.0e-05
lr_after_warmup: 0.0005
model_path: /content/drive/MyDrive/Colab Notebooks/Models/MyModel
num_heads: 8
num_layers: 4
train_epochs: 20
warmup_epochs: 2
